### ISSUE TITLE
This addin is not compatible with latest NPP+ 8.4.8

### ISSUE THREAD

**Issue by ketankbc** [maindolaamit/NPP_Templates#1]
Please port the code to new NPP version and publish the plugin here or sourceforge.
Thanks in advance.

**Comment by ketankbc** [comment]
mistake.

**Comment by maindolaamit** [comment]
Hello Ketan,

I don't use Notepad++ anymore, I have shifted completely to LunarVIM or
VSCode as it has better plugin support.
I did not create any plugins  back then, I just updated the existing
plugin.

Regards,
Amit Maindola
